In [3]:
import pandas as pd
import numpy as np
import h5py as h5
from scipy.interpolate import RegularGridInterpolator as rgi

In [4]:
extmapf=h5.File('stilism_cube.h5','r')

In [5]:
list(extmapf.keys())

['stilism']

In [6]:
extmapg=extmapf['stilism']

In [7]:
list(extmapg.keys())

['cube_datas',
 'cube_err_distance',
 'cube_err_magnitudemax',
 'cube_err_magnitudemin']

In [8]:
extmap=extmapg['cube_datas']

In [9]:
extmap=np.array(extmap[:,:,:])

In [10]:
extmap.shape

(800, 800, 120)

In [11]:
x, y, z = np.linspace(-1997.5,1997.5,800), np.linspace(-1997.5,1997.5,800), np.linspace(-297.5,297.5,120)

In [18]:
def ext_calc(l, b, d, extmap_array, npoints):
    t = np.linspace(0, 1, npoints)
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    
    if star_pos[0] > 1997.5:
        d = 1997.49/(np.cos(b*np.pi/180)*np.cos(l*np.pi/180))
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    if star_pos[0] < -1997.5:
        d = -1997.49/(np.cos(b*np.pi/180)*np.cos(l*np.pi/180))
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    if star_pos[1] > 1997.5:
        d = 1997.49/np.cos(b*np.pi/180)*np.sin(l*np.pi/180)
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    if star_pos[1] < -1997.5:
        d = -1997.49/np.cos(b*np.pi/180)*np.sin(l*np.pi/180)
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    if star_pos[2] > 297.5:
        d = 297.49/np.sin(b*np.pi/180)
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
    if star_pos[2] < -297.5:
        d = -297.49/np.sin(b*np.pi/180)
        star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
        
    interpolation_points=np.array([star_pos[0]*t,star_pos[1]*t,star_pos[2]*t]).transpose()

    interpolator=rgi((x,y,z), extmap)

    interpolated_vals=interpolator(interpolation_points)

    extout=sum(interpolated_vals)*(d/npoints)
    
    return extout

In [19]:
l, b, d = 240.498514, 31.074842, 3017.464674
ext_calc(l,b,d,extmap,100)

0.030572897856690973

In [12]:
extmap[200:203,200:203,75]

array([[  1.02448997e-04,   1.00586003e-04,   9.75587027e-05],
       [  1.02789003e-04,   1.01992999e-04,   1.00083998e-04],
       [  1.02192003e-04,   1.02370999e-04,   1.01584999e-04]], dtype=float32)

In [13]:
x[200:203],y[200:203],z[75]

(array([-997.5, -992.5, -987.5]), array([-997.5, -992.5, -987.5]), 77.5)

In [14]:
1.01992999e-04+(1.01584999e-04-1.01992999e-04)/2

0.000101788999

In [15]:
interpolator([-990,-990,77.5])

NameError: name 'interpolator' is not defined

In [14]:
#l, b, d = 292.68034, 27.95968, 1000/7.51
#l, b, d = 279.23474, 38.78369, 1000/130.23
#l, b, d = 240.498514, 31.074842, 3017.464674
l=15.816481778478
b= -34.1145744278106
d= 655.1897216504016
extmap_array = extmap
npoints = 1000
t = np.linspace(0, 1, npoints)
star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
print(star_pos)

if star_pos[0] > 1997.5:
    d = 1997.49/(np.cos(b*np.pi/180)*np.cos(l*np.pi/180))
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
if star_pos[0] < -1997.5:
    d = -1997.49/(np.cos(b*np.pi/180)*np.cos(l*np.pi/180))
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
if star_pos[1] > 1997.5:
    d = 1997.49/np.cos(b*np.pi/180)*np.sin(l*np.pi/180)
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
if star_pos[1] < -1997.5:
    d = -1997.49/np.cos(b*np.pi/180)*np.sin(l*np.pi/180)
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
if star_pos[2] > 297.5:
    d = 297.49/np.sin(b*np.pi/180)
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
if star_pos[2] < -297.5:
    d = -297.49/np.sin(b*np.pi/180)
    star_pos = d*np.array([np.cos(b*np.pi/180)*np.cos(l*np.pi/180),np.cos(b*np.pi/180)*np.sin(l*np.pi/180),np.sin(b*np.pi/180)])
print(star_pos)
interpolation_points=np.array([star_pos[0]*t,star_pos[1]*t,star_pos[2]*t]).transpose()

interpolator=rgi((x,y,z), extmap)

interpolated_vals=interpolator(interpolation_points)

extout=sum(interpolated_vals)*(d/npoints)

[ 521.90606615  147.84669741 -367.4629009 ]
[ 422.52383911  119.69348172 -297.49      ]


In [82]:
extout

0.038503040508387619

In [70]:
star_pos

array([-953.06364702, -488.14131379, -297.5       ])

In [13]:
interpolation_points

array([[  0.00000000e+00,   0.00000000e+00,  -0.00000000e+00],
       [  4.22961003e-01,   1.19817322e-01,  -2.97797798e-01],
       [  8.45922006e-01,   2.39634645e-01,  -5.95595596e-01],
       ..., 
       [  4.21692120e+02,   1.19457871e+02,  -2.96904404e+02],
       [  4.22115081e+02,   1.19577688e+02,  -2.97202202e+02],
       [  4.22538042e+02,   1.19697505e+02,  -2.97500000e+02]])

In [74]:
interpolated_vals

array([  1.07616424e-05,   9.58069758e-06,   8.37221699e-06,
         7.41625689e-06,   6.93818557e-06,   6.49196867e-06,
         6.20728907e-06,   5.94982260e-06,   5.73082014e-06,
         5.74434397e-06,   5.78222830e-06,   5.81809763e-06,
         5.85154221e-06,   5.88215233e-06,   6.05584463e-06,
         6.23897959e-06,   6.44499161e-06,   6.65451878e-06,
         6.84940719e-06,   7.08442199e-06,   7.33160447e-06,
         7.56178133e-06,   7.77504368e-06,   7.97148259e-06,
         8.16229517e-06,   8.34977826e-06,   8.55883398e-06,
         8.78052528e-06,   8.98828667e-06,   9.18319627e-06,
         9.37191708e-06,   9.54979873e-06,   9.71707202e-06,
         9.87396779e-06,   1.00207169e-05,   1.01693783e-05,
         1.03219102e-05,   1.05208390e-05,   1.07137663e-05,
         1.09012203e-05,   1.10748022e-05,   1.12400912e-05,
         1.14018244e-05,   1.15789595e-05,   1.17530622e-05,
         1.19252192e-05,   1.20951045e-05,   1.23032010e-05,
         1.25133636e-05,

In [72]:
1000/0.8

1250.0